INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Elephants", "Conservation",10000, "August 1,2017", "November 1,2017");

INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);
INSERT INTO users (name,age) VALUES ("Paul", 25);


INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,4,9);
